/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Scott
 */
public class GraphColorChooserDialog11 extends javax.swing.JDialog {
    
    private Color vertexFillColor;
    private Color vertexStrokeColor;
    private Color edgeStrokeColor;
    //Create a new SampleCanvas object
    private views.SampleCanvas sampleCanvas;
    
    /**
     * Creates new form GraphColorChooserDialog
     */
    public GraphColorChooserDialog11(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //add the sampleCanvas object to the jScrollPane
        sampleCanvas = new views.SampleCanvas();
        sampleCanvas.setColumns(20);
        sampleCanvas.setRows(5);
        sampleCanvasScrollPane.setViewportView(sampleCanvas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        sampleCanvasScrollPane = new javax.swing.JScrollPane();
        colorChooserPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okButton.setText("OK");

        cancelButton.setText("Cancel");

        sampleCanvasScrollPane.setEnabled(false);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        colorChooserPanel.setLayout(jPanel1Layout);

        jLabel4.setText("Vertex Fill Color:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        colorChooserPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Vertex Stroke Color:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        colorChooserPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Edge Stroke Color:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        colorChooserPanel.add(jLabel6, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorChooserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addComponent(sampleCanvasScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampleCanvasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel colorChooserPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane sampleCanvasScrollPane;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JComboBox vertexFillColorComboBox;
    private javax.swing.JComboBox vertexStrokeColorComboBox;
    private javax.swing.JComboBox edgeStrokeColorComboBox;
    
    public JButton getCancelButton() {
        return cancelButton;
    }

    public JButton getOKButton() {
        return okButton;
    }

    public SampleCanvas getSampleCanvas() {
        return sampleCanvas;
    }
    
    public Color getVertexFillColor() {
        return vertexFillColor;
    }

    public Color getVertexStrokeColor() {
        return vertexStrokeColor;
    }
    
    public Color getEdgeStrokeColor() {
        return edgeStrokeColor;
    }
    
    /**
     * Sets the dialog's vertexFillColor, the sampleCanvas's vertexFillColor,
     * and the text field background
     * @param vertexFillColor 
     */
    public void setVertexFillColor(Color vertexFillColor) {
        this.vertexFillColor = vertexFillColor;
        sampleCanvas.setVertexFillColor(vertexFillColor);
        vertexFillColorComboBox.setSelectedItem(vertexFillColor);
    }

    /**
     * Sets the dialog's vertexStrokeColor, the sampleCanvas's vertexStrokeColor,
     * and the text field background
     * @param vertexStrokeColor 
     */
    public void setVertexStrokeColor(Color vertexStrokeColor) {
        this.vertexStrokeColor = vertexStrokeColor;
        sampleCanvas.setVertexStrokeColor(vertexStrokeColor);
        vertexStrokeColorComboBox.setSelectedItem(vertexStrokeColor);
    }
    
    /**
     * Sets the dialog's edgeStrokeColor, the sampleCanvas's edgeStrokeColor,
     * and the text field background
     * @param edgeStrokeColor 
     */
    public void setEdgeStrokeColor(Color edgeStrokeColor) {
        this.edgeStrokeColor = edgeStrokeColor;
        sampleCanvas.setEdgeStrokeColor(edgeStrokeColor);
        edgeStrokeColorComboBox.setSelectedItem(edgeStrokeColor);
    }

    public JPanel getColorChooserPanel() {
        return colorChooserPanel;
    }

    public JComboBox getVertexFillColorComboBox() {
        return vertexFillColorComboBox;
    }

    public JComboBox getVertexStrokeColorComboBox() {
        return vertexStrokeColorComboBox;
    }

    public JComboBox getEdgeStrokeColorComboBox() {
        return edgeStrokeColorComboBox;
    }
}
